//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrameenaVidya.UserHome {
    
    
    public partial class MyProfile {
        
        /// <summary>
        /// MyProfile1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GrameenaVidya.Controls.MyProfile MyProfile1;
        
        /// <summary>
        /// ChangePassword111 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GrameenaVidya.Controls.ChangePassword1 ChangePassword111;
    }
}
