//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrameenaVidya.Programs {
    
    
    public partial class DigitalInclusion {
        
        /// <summary>
        /// SocialMedia1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GrameenaVidya.Controls.SocialMedia SocialMedia1;
        
        /// <summary>
        /// DigitalInclusion_right1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GrameenaVidya.Controls.DigitalInclusion_right DigitalInclusion_right1;
    }
}
